Header stamp
uint16 ID

string ext_config

float32 accel_x
float32 accel_y
float32 accel_z
float32 v_batt
float64 alt

float32 gyro_x
float32 gyro_y
float32 gyro_z

# yaw counter clockwise is positive
float32 yaw
# pitch up is positive
float32 pitch
# roll right is positive
float32 roll

# X(forward), Y(left)
float32 kalman_vx
float32 kalman_vy

# X(forward), Y(left), Z(up)
float32 pos_x
float32 pos_y
float32 pos_z

float32 magx
float32 magy
float32 magz