set(_CATKIN_CURRENT_PACKAGE "crazyflie")
set(crazyflie_VERSION "0.0.0")
set(crazyflie_MAINTAINER "suneel <suneel@todo.todo>")
set(crazyflie_PACKAGE_FORMAT "1")
set(crazyflie_BUILD_DEPENDS "rospy" "message_generation" "sensor_msgs" "std_msgs")
set(crazyflie_BUILD_EXPORT_DEPENDS "rospy" "message_runtime" "sensor_msgs" "std_msgs")
set(crazyflie_BUILDTOOL_DEPENDS "catkin")
set(crazyflie_BUILDTOOL_EXPORT_DEPENDS )
set(crazyflie_EXEC_DEPENDS "rospy" "message_runtime" "sensor_msgs" "std_msgs")
set(crazyflie_RUN_DEPENDS "rospy" "message_runtime" "sensor_msgs" "std_msgs")
set(crazyflie_TEST_DEPENDS )
set(crazyflie_DOC_DEPENDS )
set(crazyflie_DEPRECATED "")